#!/usr/bin/env python3

import pandas as pd
import sys
import subprocess
from pathlib import Path
from datetime import datetime


def format_depth(depth_val):
    """Format depth value, handling both numeric and string values like 'ALL'."""
    if isinstance(depth_val, str):
        return depth_val.upper()
    else:
        return f"{depth_val:.0f}"


def get_results_dir(collection_name=None):
    """Get results directory based on collection name or from config."""
    if collection_name:
        # Get base folder from config and append collection name
        script_dir = Path(__file__).parent.parent / "scripts"
        config_script = script_dir / "dataset_config.sh"

        if config_script.exists():
            cmd = f'source "{config_script}" && echo "$FOLDER"'
            result = subprocess.run(
                ["bash", "-c", cmd], capture_output=True, text=True, check=True
            )
            base_folder = Path(result.stdout.strip())
            return base_folder / "grid_results" / collection_name

    # If no collection name or config not found, use current directory
    return Path(".")


def load_data():
    """Load the 3 summary files generated by evaluate_grid_results.sh."""
    data = {}

    # Expected files (matching our evaluate_grid_results.sh output)
    files = {
        "baseline": RESULTS_DIR / "baseline.tsv",
        "monot5": RESULTS_DIR / "monot5.tsv",
        "prf": RESULTS_DIR / "prf.tsv",
    }

    for key, filepath in files.items():
        if filepath.exists():
            try:
                df = pd.read_csv(filepath, sep="\t")
                if len(df) > 0:
                    data[key] = df
                    print(
                        f"✓ Loaded {len(df)} {key} configurations from {filepath.name}"
                    )
            except Exception as e:
                print(f"Warning: Could not load {filepath}: {e}")
        else:
            print(f"Warning: File not found: {filepath}")

    if len(data) == 0:
        print("Error: No summary files could be loaded")
        print("Please run evaluate_grid_results.sh first")
        sys.exit(1)

    return data


def generate_overview(data):
    """Generate overview section."""
    lines = ["## Overview\n"]

    if "baseline" in data:
        lines.append(f"- **Baseline configurations**: {len(data['baseline'])}")

    if "monot5" in data:
        lines.append(f"- **MonoT5 Rerank configurations**: {len(data['monot5'])}")

    if "prf" in data:
        # Count by RF model
        rf_models = data["prf"]["rf_model"].unique()
        lines.append(f"- **PRF configurations**: {len(data['prf'])}")
        for rf_model in rf_models:
            count = len(data["prf"][data["prf"]["rf_model"] == rf_model])
            lines.append(f"  - **{rf_model}**: {count}")

    total = sum(len(df) for df in data.values())
    lines.append(f"- **Total experiments**: {total}\n")

    return lines


def generate_parameter_ranges(data):
    """Generate parameter ranges section."""
    lines = ["## Parameter Ranges\n"]

    # For PRF strategies
    if "prf" in data:
        prf_df = data["prf"]

        for rf_model in prf_df["rf_model"].unique():
            rf_data = prf_df[prf_df["rf_model"] == rf_model]

            # Handle depths that might be 'ALL' or other string values
            depths = []
            for x in sorted(rf_data["depth"].unique()):
                if isinstance(x, str) and x.upper() == "ALL":
                    depths.append("ALL")
                else:
                    depths.append(int(x))

            e_values = [int(x) for x in sorted(rf_data["e"].unique())]

            lines.append(f"### {rf_model}")
            lines.append(f"- **Depths (k)**: {depths}")
            lines.append(f"- **Expansion terms (e)**: {e_values}")

            # Add lambda parameter if present
            if "lambda" in rf_data.columns and rf_data["lambda"].notna().any():
                lambdas = [float(x) for x in sorted(rf_data["lambda"].unique())]
                lines.append(f"- **Lambda (λ)**: {lambdas}")

            lines.append("")

    # MonoT5 Reranker
    if "monot5" in data:
        # Handle depths that might be 'ALL' or other string values
        depths = []
        for x in sorted(data["monot5"]["depth"].unique()):
            if isinstance(x, str) and x.upper() == "ALL":
                depths.append("ALL")
            else:
                depths.append(int(x))
        lines.append("### MonoT5 Reranker")
        lines.append(f"- **Depths**: {depths}\n")

    return lines


def generate_baseline_report(baseline_df):
    """Generate baseline comparison report."""
    if baseline_df is None or len(baseline_df) == 0:
        return []

    lines = ["## Baseline Results\n"]

    for _, row in baseline_df.iterrows():
        baseline = row["baseline"]
        map_score = row["map"]
        p10_score = row["P@10"]
        ndcg100_score = row["ndcg@100"]

        lines.append(f"**{baseline}:**")
        lines.append(f"- MAP: {map_score:.4f}")
        lines.append(f"- P@10: {p10_score:.4f}")
        lines.append(f"- nDCG@100: {ndcg100_score:.4f}")
        lines.append("")

    # Find best baseline for each metric
    if len(baseline_df) > 1:
        best_map = baseline_df.loc[baseline_df["map"].idxmax()]
        best_p10 = baseline_df.loc[baseline_df["P@10"].idxmax()]
        best_ndcg = baseline_df.loc[baseline_df["ndcg@100"].idxmax()]

        lines.append("**Best performing baselines:**")
        lines.append(f"- MAP: {best_map['baseline']} ({best_map['map']:.4f})")
        lines.append(f"- P@10: {best_p10['baseline']} ({best_p10['P@10']:.4f})")
        lines.append(
            f"- nDCG@100: {best_ndcg['baseline']} ({best_ndcg['ndcg@100']:.4f})"
        )
        lines.append("")

    return lines


def generate_best_configurations(data):
    """Generate best configurations section."""
    lines = ["## Best Configurations by Metric\n"]

    # Get baseline reference if available
    baseline_ref = None
    if "baseline" in data and len(data["baseline"]) > 0:
        baseline_ref = data["baseline"].iloc[0]

    for metric in ["map", "P@10", "ndcg@100"]:
        lines.append(f"### By {metric.upper()}\n")

        all_configs = []

        # Baseline
        if "baseline" in data:
            for _, row in data["baseline"].iterrows():
                all_configs.append(
                    {
                        "type": "Baseline",
                        "name": row["baseline"],
                        "details": "",
                        "value": row[metric],
                        "full_scores": f"MAP: {row['map']:.4f}, P@10: {row['P@10']:.4f}, nDCG@100: {row['ndcg@100']:.4f}",
                    }
                )

        # MonoT5
        if "monot5" in data:
            best_monot5 = data["monot5"].loc[data["monot5"][metric].idxmax()]
            all_configs.append(
                {
                    "type": "MonoT5 Rerank",
                    "name": f"{best_monot5['baseline']}",
                    "details": f"depth={format_depth(best_monot5['depth'])}",
                    "value": best_monot5[metric],
                    "full_scores": f"MAP: {best_monot5['map']:.4f}, P@10: {best_monot5['P@10']:.4f}, nDCG@100: {best_monot5['ndcg@100']:.4f}",
                }
            )

        # PRF
        if "prf" in data:
            for rf_model in data["prf"]["rf_model"].unique():
                rf_data = data["prf"][data["prf"]["rf_model"] == rf_model]
                best_prf = rf_data.loc[rf_data[metric].idxmax()]

                details_parts = [
                    f"strategy={best_prf['strategy']}",
                    f"depth={format_depth(best_prf['depth'])}",
                    f"e={best_prf['e']:.0f}",
                ]

                if "lambda" in best_prf and pd.notna(best_prf["lambda"]):
                    details_parts.append(f"λ={best_prf['lambda']:.2f}")

                all_configs.append(
                    {
                        "type": f"PRF {rf_model}",
                        "name": f"{best_prf['baseline']}",
                        "details": ", ".join(details_parts),
                        "value": best_prf[metric],
                        "full_scores": f"MAP: {best_prf['map']:.4f}, P@10: {best_prf['P@10']:.4f}, nDCG@100: {best_prf['ndcg@100']:.4f}",
                    }
                )

        # Sort by metric value
        all_configs.sort(key=lambda x: x["value"], reverse=True)

        # Display top configurations
        for i, config in enumerate(all_configs[:10], 1):
            lines.append(f"**{i}. {config['type']} - {config['name']}**")
            if config["details"]:
                lines.append(f"   {config['details']}")
            lines.append(f"   **{metric.upper()}**: {config['value']:.4f}")
            lines.append(f"   {config['full_scores']}")

            # Show improvement over baseline
            if baseline_ref is not None and config["type"] != "Baseline":
                improvement = (
                    (config["value"] - baseline_ref[metric]) / baseline_ref[metric]
                ) * 100
                lines.append(f"   Improvement: {improvement:+.2f}%")
            lines.append("")

    return lines


def generate_prf_analysis(prf_df):
    """Generate detailed PRF analysis."""
    if prf_df is None or len(prf_df) == 0:
        return []

    lines = ["## PRF Strategy Analysis\n"]

    for rf_model in prf_df["rf_model"].unique():
        rf_data = prf_df[prf_df["rf_model"] == rf_model]
        lines.append(f"### {rf_model} Analysis\n")

        # Strategy performance
        lines.append("#### Performance by Strategy\n")
        lines.append("| Strategy | Best MAP | Avg MAP | Best P@10 | Avg P@10 |")
        lines.append("|----------|----------|---------|-----------|----------|")

        for strategy in rf_data["strategy"].unique():
            strategy_data = rf_data[rf_data["strategy"] == strategy]
            best_map = strategy_data["map"].max()
            avg_map = strategy_data["map"].mean()
            best_p10 = strategy_data["P@10"].max()
            avg_p10 = strategy_data["P@10"].mean()

            lines.append(
                f"| {strategy} | {best_map:.4f} | {avg_map:.4f} | {best_p10:.4f} | {avg_p10:.4f} |"
            )

        lines.append("")

        # Parameter analysis
        if len(rf_data) > 1:
            lines.append("#### Parameter Analysis\n")

            # Depth analysis
            lines.append("**By Depth:**\n")
            depth_stats = rf_data.groupby("depth")[["map", "P@10"]].agg(["mean", "max"])
            lines.append("| Depth | MAP (avg) | MAP (max) | P@10 (avg) | P@10 (max) |")
            lines.append("|-------|-----------|-----------|------------|------------|")
            for depth in sorted(rf_data["depth"].unique()):
                stats = depth_stats.loc[depth]
                lines.append(
                    f"| {format_depth(depth)} | {stats[('map', 'mean')]:.4f} | {stats[('map', 'max')]:.4f} | {stats[('P@10', 'mean')]:.4f} | {stats[('P@10', 'max')]:.4f} |"
                )
            lines.append("")

            # E analysis
            lines.append("**By Expansion Terms (e):**\n")
            e_stats = rf_data.groupby("e")[["map", "P@10"]].agg(["mean", "max"])
            lines.append("| E | MAP (avg) | MAP (max) | P@10 (avg) | P@10 (max) |")
            lines.append("|---|-----------|-----------|------------|------------|")
            for e in sorted(rf_data["e"].unique()):
                stats = e_stats.loc[e]
                lines.append(
                    f"| {e:.0f} | {stats[('map', 'mean')]:.4f} | {stats[('map', 'max')]:.4f} | {stats[('P@10', 'mean')]:.4f} | {stats[('P@10', 'max')]:.4f} |"
                )
            lines.append("")

            # Lambda analysis (if applicable)
            if "lambda" in rf_data.columns and rf_data["lambda"].notna().any():
                lines.append("**By Lambda (λ):**\n")
                lambda_stats = rf_data.groupby("lambda")[["map", "P@10"]].agg(
                    ["mean", "max"]
                )
                lines.append(
                    "| Lambda | MAP (avg) | MAP (max) | P@10 (avg) | P@10 (max) |"
                )
                lines.append(
                    "|--------|-----------|-----------|------------|------------|"
                )
                for lam in sorted(rf_data["lambda"].unique()):
                    if pd.notna(lam):
                        stats = lambda_stats.loc[lam]
                        lines.append(
                            f"| {lam:.2f} | {stats[('map', 'mean')]:.4f} | {stats[('map', 'max')]:.4f} | {stats[('P@10', 'mean')]:.4f} | {stats[('P@10', 'max')]:.4f} |"
                        )
                lines.append("")

        # Top 5 configurations
        lines.append(f"#### Top 5 {rf_model} Configurations (by MAP)\n")
        lines.append(
            "| Rank | Baseline | Strategy | Depth | E | Lambda | MAP | P@10 | nDCG@100 |"
        )
        lines.append(
            "|------|----------|----------|-------|---|--------|-----|------|---------|"
        )

        top5 = rf_data.nlargest(5, "map")
        for idx, (_, row) in enumerate(top5.iterrows(), 1):
            lambda_str = f"{row['lambda']:.2f}" if pd.notna(row["lambda"]) else "N/A"
            lines.append(
                f"| {idx} | {row['baseline']} | {row['strategy']} | {format_depth(row['depth'])} | {row['e']:.0f} | {lambda_str} | {row['map']:.4f} | {row['P@10']:.4f} | {row['ndcg@100']:.4f} |"
            )

        lines.append("")

    return lines


def generate_overall_summary(data):
    """Generate overall summary comparing all approaches."""
    lines = ["## Overall Summary\n"]

    all_results = []

    # Collect all results
    if "baseline" in data:
        for _, row in data["baseline"].iterrows():
            all_results.append(
                {
                    "approach": f"{row['baseline']} baseline",
                    "map": row["map"],
                    "p10": row["P@10"],
                    "ndcg100": row["ndcg@100"],
                }
            )

    if "monot5" in data:
        for _, row in data["monot5"].iterrows():
            all_results.append(
                {
                    "approach": f"{row['baseline']} + MonoT5 (depth={format_depth(row['depth'])})",
                    "map": row["map"],
                    "p10": row["P@10"],
                    "ndcg100": row["ndcg@100"],
                }
            )

    if "prf" in data:
        for _, row in data["prf"].iterrows():
            lambda_str = f", λ={row['lambda']:.2f}" if pd.notna(row["lambda"]) else ""
            all_results.append(
                {
                    "approach": f"{row['baseline']} + {row['rf_model']} ({row['strategy']}, depth={format_depth(row['depth'])}, e={row['e']:.0f}{lambda_str})",
                    "map": row["map"],
                    "p10": row["P@10"],
                    "ndcg100": row["ndcg@100"],
                }
            )

    # Sort by MAP
    all_results.sort(key=lambda x: x["map"], reverse=True)

    lines.append("### Top 10 Configurations by MAP\n")
    lines.append("| Rank | Approach | MAP | P@10 | nDCG@100 |")
    lines.append("|------|----------|-----|------|---------|")

    for i, result in enumerate(all_results[:10], 1):
        lines.append(
            f"| {i} | {result['approach']} | {result['map']:.4f} | {result['p10']:.4f} | {result['ndcg100']:.4f} |"
        )

    lines.append("")
    return lines


def generate_report(data, collection_name=None):
    """Generate complete report."""
    report = []

    # Extract dataset name from collection_name
    dataset_display = (
        collection_name.replace("_index", "").upper() if collection_name else "Unknown"
    )

    # Header
    report.append(f"# Grid Search Results Report - {dataset_display}")
    report.append(f"\n**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

    # Overview
    report.extend(generate_overview(data))

    # Parameter ranges
    report.extend(generate_parameter_ranges(data))

    # Baseline results
    if "baseline" in data:
        report.extend(generate_baseline_report(data["baseline"]))

    # Best configurations
    report.extend(generate_best_configurations(data))

    # PRF analysis
    if "prf" in data:
        report.extend(generate_prf_analysis(data["prf"]))

    # Overall summary
    report.extend(generate_overall_summary(data))

    return "\n".join(report)


# Parse command line arguments
collection_name = None
if len(sys.argv) > 1:
    if sys.argv[1] in ["-h", "--help"]:
        print(__doc__)
        sys.exit(0)
    else:
        collection_name = sys.argv[1]
        print(f"Using collection: {collection_name}")
else:
    print("No collection specified, using default configuration")

# Configuration
RESULTS_DIR = get_results_dir(collection_name)

print(f"Loading results from: {RESULTS_DIR}")
print()

# Load data
data = load_data()
print()

# Generate report
print("Generating report...")
report_content = generate_report(data, collection_name)

# Print report
print(report_content)

# Save report to file
report_file = RESULTS_DIR / "grid_search_report.txt"
with open(report_file, "w") as f:
    f.write(report_content)

print(f"\nReport saved to: {report_file}")
